### ISSUE TITLE
dev dependencies question

### ISSUE THREAD

**Issue by landsman** [vaadin/skeleton-starter-hilla-react#221]
Hello guys,

I just clonned the repository via hilla cli and look at package.json.
My first question was:

"Why these packages with generator name are not under dev dependencies?"

https://github.com/vaadin/skeleton-starter-hilla-react/blob/v2/package.json#L8-L16

```json
    "@hilla/generator-typescript-cli": "2.5.7",
    "@hilla/generator-typescript-core": "2.5.7",
    "@hilla/generator-typescript-plugin-backbone": "2.5.7",
    "@hilla/generator-typescript-plugin-barrel": "2.5.7",
    "@hilla/generator-typescript-plugin-client": "2.5.7",
    "@hilla/generator-typescript-plugin-model": "2.5.7",
    "@hilla/generator-typescript-plugin-push": "2.5.7",
    "@hilla/generator-typescript-plugin-subtypes": "2.5.7",
    "@hilla/generator-typescript-utils": "2.5.7",
```

Can you reply please?

**Comment by taefi** [comment]
No comment about the v2.5, but the good news is that with the new 24.4 they are now in the devDependencies:
https://github.com/vaadin/skeleton-starter-hilla-react/blob/v24.4/package.json#L39

**Comment by landsman** [comment]
wow from version 2 to 24? how does this happen?

**Comment by taefi** [comment]
>  wow from version 2 to 24? how does this happen?

This was the result of adopting Hilla as part of the Vaadin Platform, so that Flow and Hilla can coexist in the same application. Of course, if someone wants to continue using either of them without getting involved with the other one, it is also possible.

**Comment by taefi** [comment]
@landsman Btw, you can ask this types of questions on Vaadin Forum to get faster answers: 
https://vaadin.com/forum/c/hilla/18

**Comment by landsman** [comment]
cool, do you have some expected release date of this version?

**Comment by Artur-** [comment]
https://twitter.com/leifastrand/status/1783719215679373378
